version: 2

multi-ecosystem-groups:
  all-version-updates:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "maven"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-version-updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-version-updates"
