name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'release/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cli:
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    uses: ./.github/workflows/build-cli.yml
